version: '3.7'
services:
  database:
    image: mysql:8.4
    volumes:
      - mysql:/var/lib/mysql
      - ./machine/my.cnf:/etc/alternatives/my.cnf
    ports:
      - "3306:3306"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=aluno
      - MYSQL_USER=aluno
      - MYSQL_PASSWORD=aluno

volumes:
  mysql: